"use client";

import { Activity, AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, CircleOff, Clock3, Database, ExternalLink, Film, LoaderCircle, Menu, Play, RefreshCw, Search, ShieldCheck, ShieldX, Sparkles, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type VideoStatus = "DISCOVERED" | "VALIDATING" | "READY" | "REJECTED" | "QUEUED" | "PROCESSING" | "SAMPLED_SAFE" | "SAMPLED_NSFW" | "ERROR";
type Video = { id:number; title:string; page_url:string; video_url:string; resolved_video_url:string|null; content_type:string|null; size_bytes:number|null; duration_seconds:number|null; accepts_ranges:boolean|null; status:VideoStatus; nsfw_score:number|null; nsfw_average_score:number|null; nsfw_positive_frames:number; nsfw_model:string|null; sampled_frames:number; task_id:string|null; error_message:string|null; created_at:string; updated_at:string; };
type VideoPage = { items:Video[]; page:number; size:number; total:number; pages:number; };

const statusLabels: Record<VideoStatus,string> = { DISCOVERED:"Découverte", VALIDATING:"Validation", READY:"Prête", REJECTED:"Rejetée", QUEUED:"En file", PROCESSING:"Analyse", SAMPLED_SAFE:"Sûre", SAMPLED_NSFW:"NSFW", ERROR:"Erreur" };
const activeStatuses: VideoStatus[] = ["VALIDATING","QUEUED","PROCESSING"];

async function api<T>(path:string, init?:RequestInit):Promise<T> { const response=await fetch(`/api/backend${path}`,{...init,headers:{"Content-Type":"application/json",...init?.headers}}); if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.detail??`Erreur HTTP ${response.status}`)} return response.status===204?(undefined as T):response.json(); }
function formatBytes(bytes:number|null){if(bytes===null)return "—";const units=["o","Ko","Mo","Go"];let value=bytes,index=0;while(value>=1024&&index<units.length-1){value/=1024;index++}return `${value.toFixed(index>1?1:0)} ${units[index]}`}
function formatDuration(seconds:number|null){if(seconds===null)return "—";return `${Math.floor(seconds/60)} min ${Math.round(seconds%60).toString().padStart(2,"0")} s`}
function StatusBadge({status}:{status:VideoStatus}){const Icon=status==="SAMPLED_SAFE"?ShieldCheck:status==="SAMPLED_NSFW"?ShieldX:status==="ERROR"||status==="REJECTED"?CircleOff:activeStatuses.includes(status)?LoaderCircle:CheckCircle2;return <span className={`status-badge status-${status.toLowerCase()}`}><Icon size={14} className={activeStatuses.includes(status)?"spin":""}/>{statusLabels[status]}</span>}

export default function Dashboard(){
  const [data,setData]=useState<VideoPage>({items:[],page:1,size:10,total:0,pages:0}); const [page,setPage]=useState(1); const [search,setSearch]=useState(""); const [status,setStatus]=useState<VideoStatus|"">(""); const [pageUrl,setPageUrl]=useState(""); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [actingId,setActingId]=useState<number|null>(null); const [error,setError]=useState<string|null>(null); const [lastRefresh,setLastRefresh]=useState<Date|null>(null); const [mobileMenu,setMobileMenu]=useState(false);
  const loadVideos=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);const params=new URLSearchParams({page:String(page),size:"10"});if(search.trim())params.set("search",search.trim());if(status)params.set("status",status);try{setData(await api<VideoPage>(`/api/v1/videos?${params}`));setLastRefresh(new Date());setError(null)}catch(reason){setError(reason instanceof Error?reason.message:"API indisponible")}finally{setLoading(false)}},[page,search,status]);
  useEffect(()=>{const timeout=window.setTimeout(()=>loadVideos(),250);return()=>window.clearTimeout(timeout)},[loadVideos]); useEffect(()=>{const interval=window.setInterval(()=>loadVideos(true),5000);return()=>window.clearInterval(interval)},[loadVideos]);
  const metrics=useMemo(()=>({safe:data.items.filter(v=>v.status==="SAMPLED_SAFE").length,nsfw:data.items.filter(v=>v.status==="SAMPLED_NSFW").length,active:data.items.filter(v=>activeStatuses.includes(v.status)).length}),[data.items]);
  async function scrape(event:FormEvent){event.preventDefault();if(!pageUrl.trim())return;setSubmitting(true);try{await api("/api/v1/scraping/discover",{method:"POST",body:JSON.stringify({page_url:pageUrl.trim()})});setPageUrl("");setPage(1);await loadVideos()}catch(reason){setError(reason instanceof Error?reason.message:"Scraping impossible")}finally{setSubmitting(false)}}
  async function runAction(video:Video){setActingId(video.id);try{if(video.status==="DISCOVERED")await api(`/api/v1/videos/${video.id}/validate`,{method:"POST"});else if(video.status==="READY")await api(`/api/v1/videos/${video.id}/enqueue`,{method:"POST"});await loadVideos(true)}catch(reason){setError(reason instanceof Error?reason.message:"Action impossible")}finally{setActingId(null)}}
  return <div className="app-shell">
    <aside className={`sidebar ${mobileMenu?"sidebar-open":""}`}><div className="brand"><span className="brand-mark"><ShieldCheck size={20}/></span><span>Sentinel<span>Video</span></span></div><button className="mobile-close" onClick={()=>setMobileMenu(false)} aria-label="Fermer le menu"><X/></button><nav aria-label="Navigation principale"><a className="nav-item active" href="#dashboard"><Activity size={19}/>Vue d’ensemble</a><a className="nav-item" href="#videos"><Film size={19}/>Vidéos <span className="nav-count">{data.total}</span></a><a className="nav-item" href="#collecte"><Search size={19}/>Collecte</a></nav><div className="sidebar-spacer"/><div className="system-card"><div className="system-icon"><Database size={18}/></div><div><strong>Pipeline actif</strong><span>SQLite · Redis · ViT</span></div><span className="online-dot"/></div><p className="sidebar-foot">Modération échantillonnée<br/>Décision assistée par IA</p></aside>
    {mobileMenu&&<button className="backdrop" onClick={()=>setMobileMenu(false)} aria-label="Fermer"/>}
    <main className="main-content" id="dashboard"><header className="topbar"><button className="menu-button" onClick={()=>setMobileMenu(true)} aria-label="Ouvrir le menu"><Menu/></button><div><p className="eyebrow">Centre de contrôle</p><h1>Analyse des vidéos</h1></div><div className="topbar-actions"><span className="refresh-copy"><Clock3 size={15}/>{lastRefresh?`Actualisé à ${lastRefresh.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}`:"Connexion…"}</span><button className="icon-button" onClick={()=>loadVideos()} aria-label="Actualiser"><RefreshCw size={18} className={loading?"spin":""}/></button></div></header>
      {error&&<div className="error-banner"><AlertTriangle size={18}/><span><strong>Connexion ou traitement interrompu.</strong> {error}</span><button onClick={()=>setError(null)} aria-label="Fermer"><X size={17}/></button></div>}
      <section className="metrics-grid" aria-label="Indicateurs"><article className="metric-card"><span className="metric-icon total"><Film/></span><div><span>Vidéos recensées</span><strong>{data.total}</strong><small>dans la base locale</small></div></article><article className="metric-card"><span className="metric-icon safe"><ShieldCheck/></span><div><span>Échantillons sûrs</span><strong>{metrics.safe}</strong><small>sur cette page</small></div></article><article className="metric-card"><span className="metric-icon unsafe"><ShieldX/></span><div><span>Alertes NSFW</span><strong>{metrics.nsfw}</strong><small>à examiner</small></div></article><article className="metric-card"><span className="metric-icon running"><Sparkles/></span><div><span>Traitements actifs</span><strong>{metrics.active}</strong><small>validation ou analyse</small></div></article></section>
      <section className="collect-card" id="collecte"><div className="section-heading"><span className="section-icon"><Search/></span><div><h2>Collecter une nouvelle page</h2><p>Extrayez les liens vidéo d’une page autorisée, puis lancez leur analyse.</p></div></div><form onSubmit={scrape} className="scrape-form"><label htmlFor="page-url">URL de la page source</label><div className="input-row"><div className="url-input"><ExternalLink size={18}/><input id="page-url" type="url" value={pageUrl} onChange={e=>setPageUrl(e.target.value)} placeholder="https://media.example/catalogue" required/></div><button className="primary-button" disabled={submitting}>{submitting?<LoaderCircle className="spin"/>:<Search/>}Analyser la page</button></div><p className="form-hint"><ShieldCheck size={14}/>Les adresses privées et les protocoles non sécurisés sont automatiquement bloqués.</p></form></section>
      <section className="videos-card" id="videos"><div className="section-heading table-heading"><div><h2>Vidéos détectées</h2><p>Suivez le cycle de validation et les résultats du modèle.</p></div><span className="results-count">{data.total} résultat{data.total>1?"s":""}</span></div><div className="filters"><div className="filter-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Rechercher par titre ou URL…"/></div><select value={status} onChange={e=>{setStatus(e.target.value as VideoStatus|"");setPage(1)}} aria-label="Filtrer par statut"><option value="">Tous les statuts</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
        <div className="table-wrap"><table><thead><tr><th>Vidéo</th><th>Statut</th><th>Fichier</th><th>Échantillon</th><th>Score NSFW</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{loading&&data.items.length===0?<tr><td colSpan={6}><div className="empty-state"><LoaderCircle className="spin"/><strong>Chargement des vidéos…</strong></div></td></tr>:data.items.length===0?<tr><td colSpan={6}><div className="empty-state"><Film/><strong>Aucune vidéo trouvée</strong><span>Ajoutez une page source ou modifiez vos filtres.</span></div></td></tr>:data.items.map(video=><tr key={video.id}><td><div className="video-title"><span className="video-thumb"><Play size={18} fill="currentColor"/></span><div><strong>{video.title}</strong><a href={video.page_url} target="_blank" rel="noreferrer">{new URL(video.page_url).hostname}<ExternalLink size={12}/></a></div></div></td><td><StatusBadge status={video.status}/>{video.error_message&&<span className="row-error" title={video.error_message}>Voir l’erreur</span>}</td><td><strong className="cell-main">{formatBytes(video.size_bytes)}</strong><span className="cell-sub">{video.content_type??"type inconnu"}</span></td><td><strong className="cell-main">{formatDuration(video.duration_seconds)}</strong><span className="cell-sub">{video.sampled_frames?`${video.sampled_frames} frames`:"non extrait"}</span></td><td>{video.nsfw_score===null?<span className="score-empty">—</span>:<div className="score"><strong>{Math.round(video.nsfw_score*100)}%</strong><span><i style={{width:`${video.nsfw_score*100}%`}}/></span><small>{video.nsfw_positive_frames} positive{video.nsfw_positive_frames>1?"s":""}</small></div>}</td><td>{(video.status==="DISCOVERED"||video.status==="READY")&&<button className="action-button" onClick={()=>runAction(video)} disabled={actingId===video.id}>{actingId===video.id?<LoaderCircle className="spin"/>:video.status==="DISCOVERED"?<ShieldCheck/>:<Play/>}{video.status==="DISCOVERED"?"Valider":"Analyser"}</button>}</td></tr>)}</tbody></table></div>
        <footer className="pagination"><span>Page {data.page} sur {Math.max(data.pages,1)}</span><div><button onClick={()=>setPage(v=>Math.max(1,v-1))} disabled={page<=1}><ChevronLeft/>Précédent</button><button onClick={()=>setPage(v=>v+1)} disabled={data.pages===0||page>=data.pages}>Suivant<ChevronRight/></button></div></footer></section>
    </main></div>;
}
